server:
  port: 9099
spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/halliday_ai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: auto
      table-underline: true
ai:
  stt:
    wsUrl: "ws://47.84.180.15:8000/asr?samplerate=16000"
    frameBytes: 640
    resultTimeoutMs: 5000
    azure:
      enabled: true
      subscriptionKey: "${AZURE_STT_KEY:}"
      region: "${AZURE_STT_ENDPOINT:}"
      language: "en-US"
      sampleRate: 16000
      channels: 1
      bitDepth: 16
      operationTimeoutMs: 10000
  llm:
    baseUrl: "http://47.84.180.15:3000/v1/chat/completions"
    model: "qwen3-32b"
    apiKey: "sk-ZdGyB87Wdj7FelxPuUGGjD7mDRhuDtIeNZKvxUyv3HNgKQ8c"
    temperature: 0.7
    topP: 1.0
    systemPrompt: "You are an English AI assistant. Always respond in English with concise answers."
  tts:
    url: "http://47.84.180.15:8880/v1/audio/speech"
    wsUrl: "ws://47.84.180.15:8880/v1/ws/tts/stream"
    voice: "af_heart"
    format: "pcm"
    sampleRate: 24000
    channels: 1
    bitDepth: 16
  management:
    endpoints:
      web:
        exposure:
          include: "health,info,prometheus"
